version: '3'
services:
  postgresql:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "microreso"
      POSTGRES_PASSWORD: "microreso"
      POSTGRES_DB: "microreso"
    restart: "always"
